networks:
  database:
    driver: bridge


services:

  pg-user:
    image: postgres
    environment:
      POSTGRES_DB: user-ms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
        - database
    ports:
      - "5432:5432"

  pg-email:
    image: postgres
    environment:
      POSTGRES_DB: email-ms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - database
    ports:
      - "5433:5432"