version: "3.8"

services:

  postgres-user:
    container_name: user-ms-postgresql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"