version: "3.8"

services:

  postgres-user:
    image: postgres
    environment:
      POSTGRES_DB: user-ms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  postgres-email:
    image: postgres
    environment:
      POSTGRES_DB: email-ms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"